 // Author- Tejasvi Raj Pant

const Actions = {
    GOTO_NEXT_QUESTION: 'GOTO_NEXT_QUESTION',
    GOTO_PREV_QUESTION: 'GOTO_PREV_QUESTION',
    SELECT_ANSWER: 'SELECT_ANSWER',
    DATA_FETCHED: 'DATA_FETCHED',
    RESET_QUESTION_COUNTER: 'RESET_QUESTION_COUNTER'

}

export default Actions;



